### ISSUE TITLE
head node creation failure : time out

### ISSUE THREAD

**Issue by nyue** [aws-samples/pcluster-manager#122]
I am getting these in the stack logs

![image](https://user-images.githubusercontent.com/486172/163694880-a1feb437-cb2d-4c36-8a27-27b267d76aff.png)

**Comment by charlesg3** [comment]
Hi @nyue -- You will need to look through the logs on the head node to determine where in the process it is failing to boot up which will prevent it from sending the signal to cfn init (which is why you're seeing the HeadNodeWaitCondition failure).

First select the `Logs` tab for the cluster, then take a look at the `cfn-init` and `chef-client` logs under the `HeadNode` to look for any errors.

![image](https://user-images.githubusercontent.com/6087509/163824629-17fb6cfc-9175-4cc1-82fe-a1ac928fb99a.png)

**Comment by nyue** [comment]
It appears the chef recipe for slurm installation encountered errors

![image](https://user-images.githubusercontent.com/486172/163837384-07a3f803-a0b6-4421-b3a4-3ca17c801ef9.png)

**Comment by charlesg3** [comment]
I can't see from the screenshot that you provided the slurm installation -- do you have further details as to why it failed? Is there something that is clipped off at the end of the screenshot that indicates this?

**Comment by nyue** [comment]
If you click on the image attachment, it should open up to much clearer image

Anyway, I copied the error text here

It looks like the file /opt/slurm/etc/pcluster/.slurm_plugin/clustermgtd_heartbeat is missing and chef retried 30 times to access it and then failed.

```
Recipe: aws-parallelcluster-slurm::finalize_head_node   * execute[check if clustermgtd heartbeat is available] action run[2022-04-18T15:27:05+00:00] INFO: Processing execute[check if clustermgtd heartbeat is available] action run (aws-parallelcluster-slurm::finalize_head_node line 18)      [execute] cat: /opt/slurm/etc/pcluster/.slurm_plugin/clustermgtd_heartbeat: No such file or directory
--
[2022-04-18T15:27:05+00:00] INFO: Retrying execution of execute[check if clustermgtd heartbeat is available], 29 attempts left
[execute] cat: /opt/slurm/etc/pcluster/.slurm_plugin/clustermgtd_heartbeat: No such file or directory
[2022-04-18T15:27:15+00:00] INFO: Retrying execution of execute[check if clustermgtd heartbeat is available], 28 attempts left
[execute] 2022-04-18 15:27:18.922851+0000[2022-04-18T15:27:25+00:00] INFO: execute[check if clustermgtd heartbeat is available] ran successfully      - execute cat /opt/slurm/etc/pcluster/.slurm_plugin/clustermgtd_heartbeat
```

**Comment by charlesg3** [comment]
Ah thanks -- I'd suggest checking the `clustermtg` log to see why it failed.

**Comment by nyue** [comment]
Found the reason. Placement group not support for T2 instances.

I'd thought `dryrun` would have flag such errors like it warned when DCV is enabled for certain instance sizes, this check should be part of `dryrun` for consistency and user experience.

**Comment by nyue** [comment]
@charlesg3 what about only seeing T2 instances available via pcluster-manager, are the available instance type decided by the aws-parallelcluster folks or your group ?

There are T4 instances in the ca-central region but it does not show up in pcluster-manager.

**Comment by charlesg3** [comment]
Ah we're not listing the T* instances -- we suggest C5 instances for HPC

**Comment by nyue** [comment]
So T2 will soon be removed ?

**Comment by nyue** [comment]
Or I could save the config and hand edit t2 to t4 ;-) ?

**Comment by charlesg3** [comment]
You can modify the config at the end to splice in whatever instances you want to use.

Here's the line where we are choosing the families relevant to HPC:
https://github.com/aws-samples/pcluster-manager/blob/main/api/PclusterApiHandler.py#L496

**Comment by nyue** [comment]
Aha, since you are already filtering `t2*`, switching to filtering `t3*` and `t4*` guard against Placement Group (or what ever Placement Group supports) failure and save you folks future support workload. That would be my line of thinking.

**Comment by charlesg3** [comment]
Yep -- since I don't think that many people are using t3* and t4* instances for HPC workloads that's why they aren't enabled (so that the dropdowns aren't overloaded with a ton of unused instances).

Probably possible to guard against the placement group options here on the front-end:
https://github.com/aws-samples/pcluster-manager/blob/main]/frontend/src/pages/Configure/Queues.js#L359

But would be good also to do the checks on the back-end as well (e.g. during dry-run)

**Comment by charlesg3** [comment]
I'm going to close this as the original issue has been resolved.
