### ISSUE TITLE
Tagging IAM Permission 

### ISSUE THREAD

**Issue by sean-smith** [aws-samples/pcluster-manager#196]
## Steps to Reproduce

1. Create new pcluster stack, version `3.1.4`
2. Create a cluster 

You'll see the following issue:

```bash
Resource handler returned message: "User: arn:aws:sts:::assumed-role/pc-test-ParallelClusterApi-ParallelClusterUserRole-1TRRRW39XRBG9/pc-test-ParallelClusterApi-ParallelClusterFunction-ulY7fzl6DF89 is not authorized to perform: lambda:TagResource on resource: arn:aws:lambda:eu-west-1::function:pcluster-CleanupResources-2835a040-074e-11ed-8bb2-0a9ab2ac0881 because no identity-based policy allows the lambda:TagResource action (Service: Lambda, Status Code: 403, Request ID: d379c2f4-624e-4adf-b86e-b2ee1660cc1a)" (RequestToken: 9245be36-c11b-c397-1528-d08975074c04, HandlerErrorCode: AccessDenied)
```

**Comment by sean-smith** [comment]
## Workaround

As a workaround you can add additional permissions to the Lambda function. There's a guide under [Step 3](https://pcluster.cloud/02-tutorials/02-slurm-accounting.html#step-3---add-permissions-to-your-lambda) of the Slurm accounting tutorial. If you complete step 3 you won't see this issue any longer.

**Comment by ermanno** [comment]
We are missing the permissions introduced in [this commit](https://github.com/ermanno/aws-parallelcluster/commit/205b04af9bab98d2ba2c4aeb860c0fda71712fa7), because we use a copy of the PC API template. We were using the copy because we were missing [these changes](https://github.com/aws/aws-parallelcluster/pull/3886/files), but as that is no longer the case [#198](https://github.com/aws-samples/pcluster-manager/pull/198) removes the copy of the PC API template and directly references the version hosted on S3.
