### ISSUE TITLE
Submit Job Error, no debug information shown

### ISSUE THREAD

**Issue by DBezemer** [aws-samples/pcluster-manager#63]
Using the new Submit Job dialog it returns with just an "Error: undefined" message, and a corresponding error 500 on the API Call.
CloudWatch Logs shows less than helpful information as there is no info or error message provided other than the below:
```
[ERROR] 2022-03-15T19:05:54.980Z 20825d25-cc35-457b-b808-724c73f6edf1 Exception on /manager/submit_job [POST]
File "/var/task/app.py", line 141, in submit_job_
return submit_job()
File "/var/task/api/PclusterApiHandler.py", line 245, in submit_job 
```

**Comment by DBezemer** [comment]
Most likely error is that https://github.com/aws-samples/pcluster-manager/blob/main/api/PclusterApiHandler.py#L247
Should be:
```
return resp if type(resp) == tuple else {"success": "true"}
```

**Comment by sean-smith** [comment]
@DBezemer Thanks for the bug report! Did you set the SSMInstanceCore in your config? can you post your config with specific data removed?

**Comment by charlesg3** [comment]
@DBezemer — thanks for your interest, and you’re correct in the change you suggested to propagate the error to the front end. We’ll make that fix shortly.

Separately, I’m curious if you were able to track down the root cause (perhaps difficult without the debug information). Ensuring that your cluster has the SSMInstanceCore policy (or the remote console selected) when creating the cluster is required. Separately, ensuring that the script exists or that you’ve toggled “run command” in the dialogue if you’re running a simple command are the two more likely issues.

If those aren’t the issue, and you haven’t yet tracked it down, then let’s get that fix out and see what we can do to get it working.

**Comment by charlesg3** [comment]
@DBezemer -- thanks for your interest and the catch on the bug: https://github.com/aws-samples/pcluster-manager/commit/a3c455e29b4ffb68d37240111f5a978e154e1852 should fix the issue. A new container has been pushed (but will require a new deployment of Pcluster Manager).

Feel free to open a new issue you have any further problems.

**Comment by DBezemer** [comment]
thanks, confirmed this solved the issue after redeploying the Pcluster Manager
