### ISSUE TITLE
VPC Endpoint Support

### ISSUE THREAD

**Issue by Shattoww** [aws-samples/pcluster-manager#67]
I'm in a locked down govcloud environment with no NAT gateway or public ips. I do have egress through internet gateway out to the public internet.With this being said, the nested cloudformation stack labeled (NESTED
pcluster-manager-ParallelClusterApi-132J3P9XLSR4J) is failing. I traced the problem back to ImageBuilder, it seems like there is some sort of SSM agent timeout. Not entirely sure what is happening here but I suspect the SSM service is unable to communicate with the agent on the container. I did poke through the cloudformation a bit but I didn't see anywhere I could configure vpc endpoints as I suspect this is what is needed. 

The error I get from ImageBuilder is this:

"SSM execution '8787352-dcvd-4325-5235-32525gd' failed with status = 'TimedOut' in state = 'BUILDING' and failure message = 'SSM Agent verification failed'"

**Comment by sean-smith** [comment]
@Shattoww Currently imagebuilder uses the default VPC. My guess is this is the issue since it's not using the one you've configured with the IGW. We've got a patch to change this in https://github.com/aws-samples/pcluster-manager/pull/55 however this is contingent on pcluster `3.1.3` getting released with https://github.com/aws/aws-parallelcluster/pull/3874. Should be ~2 weeks until we can support selecting the VPC.

From that PR is:
> Of note, the subnet passed in as a parameter should have internet access (i.e private subnet with NAT gateway routes, or a public subnet). When a public subnet is used, it must have MapPublicIpOnLaunch enabled as image builder won't automatically map a public IP address and the image build will timeout.

My question is if it's a private subnet with an IGW how does it reach the internet?

**Comment by Shattoww** [comment]
Indeed that was it - we re-created the default vpc to allow egress and the stack launched fine. Side note, we shuffle most of our egress traffic through some network appliances hosted in a different account for the NAT part of the equation, not that it matters. Thanks for the tip and that feature will be great as we near production.
